### ISSUE TITLE
Extra usage of useEffect

### ISSUE THREAD

**Issue by carsonliu1** [Fillet-OFish/Frontend-Capstone-Ecommerce#68]
https://github.com/Fillet-OFish/Frontend-Capstone-Ecommerce/blob/2f719b92e2cbcc3cdd0f88b45b1b395906314266/client/src/components/qa/components/AddAnswModal.jsx#L67-L69

Since uploadImgs is a state, it already rerenders the page when it gets updated with new images. There isn't a need for a useEffect to re render it a second time.

**Comment by Fernando-Gamboa** [comment]
For some reason my thumbnail images being loaded when upload is dependant on this useEffect
